package com.cosac.TestCases;

import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.event.KeyEvent;
//Here we are Creating and Verifying New Store Location in Country
import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.winium.WiniumDriver;
import org.sikuli.script.Screen;
import org.testng.Assert;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.cosac.Locators.Id;
import com.cosac.Locators.Name;
import com.cosac.Locators.Xpath;

import com.cosac.PageObject.Library;
import com.cosac.PageObject.LoginPage;
import com.cosac.Utilities.Constants;
import com.cosac.Utilities.JsonParser;
import com.cosac.Utilities.JsonReader;
import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;

import net.minidev.json.parser.ParseException;

public class COS25_NewCustomerReadyFinance extends LoginPage {

	LoginPage login = new LoginPage();
	Screen s;
	Robot robo1;
	
	// Verifying Create--> Location.
	@Test()

	public void Client()throws Throwable 
			{
		String Phone=JsonParser.CommonData("ReadyFinnanceFData.RFData.Phone");
		int coubt=Phone.length();
	    String PhoneAreaCode = Phone.substring(0, 3);
	    String PhoneNumber = Phone.substring(3, coubt);
		
		try {
			login.LoginCosacClient();
			Thread.sleep(15000);
			s = new Screen();
            robo1 = new Robot();
			

			robo1.keyPress(KeyEvent.VK_ALT);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(500);
			robo1.keyRelease(KeyEvent.VK_ALT);
			
			
			Thread.sleep(1500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_ENTER);
			log.info("User is able to click to New Customer");
			Thread.sleep(5000);

			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.CustomerID"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(700);
			// System.out.println(JsonParser.getLocation_Data("locationData.cos01.CustomerID"));
			Library.Interaction.writeKeyboard(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.PersonalID"));
			Thread.sleep(2000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.LinkingAccount"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_RIGHT);
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_RIGHT);
			Thread.sleep(300);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboard(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.DOB"));
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			// Thread.sleep(1000);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboard(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.FirstName"));
			Thread.sleep(1000);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			// Thread.sleep(1000);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboard(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.LastName"));
			// Thread.sleep(1000);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.AddressAdd"));
			s.mouseMove();
			Thread.sleep(800);
			//Library.Interaction.userWait();
			s.click();
			Thread.sleep(4000);
			robo1.keyPress(KeyEvent.VK_TAB);
			// Thread.sleep(1000);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboardString(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.Address1"));
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboardString(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.Address2"));
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			// Thread.sleep(1000);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboardString(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.Address3"));
			Thread.sleep(500);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			// Thread.sleep(1000);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboard(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.PostalCode"));
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboard(robo1, PhoneAreaCode);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			Library.Interaction.userWait();
			Library.Interaction.writeKeyboard(robo1, PhoneNumber);
			Thread.sleep(500);
			// Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			// Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);

			Library.Interaction.writeKeyboardString(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.Email"));
			Thread.sleep(300);
			// Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.CreateReadyFinance"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(12000);
			s.find(".\\target\\COS25-ReadyFinance\\arrow.png");
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(2000);
			s.rightClick();
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(8000);
			//Thread.sleep(300);
			//Personal
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(3000);
			//Residential
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.ResidentialButton"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_DELETE);
			Thread.sleep(500);
			//Library.Interaction.writeKeyboardString(robo1, "5");
			Library.Interaction.writeKeyboardString(robo1, "5");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(4000);
			s.find(".\\target\\COS25-ReadyFinance\\CurrentResidentStatus.png");
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.Employment"));
			s.mouseMove();
			Thread.sleep(300);
			s.click();
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DELETE);
			Thread.sleep(500);
			Library.Interaction.writeKeyboardString(robo1, "5");
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.EmployeeStatus"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			//Pay Frequency
			Thread.sleep(2000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.Finnancial"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "100000");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "1000");
			Thread.sleep(2000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.Category"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(2000);
			s.find(".\\target\\COS25-ReadyFinance\\ProductCategory1.png");
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(700);
			//Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(2500);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.GreenButton"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(1500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(1500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.S2"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(5000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.EmployerDetals"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "Jerry");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "Street1");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "Street2");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "234567");
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.References"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "Jack");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "Luis");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "HomeAdress1");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "HomeAdress2");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "8976554");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.Reference2"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "JackSecond");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "Luis");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "HomeAdress3");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "HomeAdress4");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "8976558");
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.Comments"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(2000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.GreenButton"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.DD"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(700);
			//Proof Of ID
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
		    Library.Interaction.writeKeyboardString(robo1, "23456780");
			Thread.sleep(300);
			//Proof of Income
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "kl097654");
			//Proof Of Address
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			Library.Interaction.writeKeyboardString(robo1, "kl09765hg");
			Thread.sleep(2000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.GreenButton"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.UW"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.Approve"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(2000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.GreenButton"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.CloseTab"));
			s.mouseMove();
			Thread.sleep(1000);
			s.click();
			Thread.sleep(4000);
			s.find(".\\target\\CustSearch\\MatchingRecord.png");
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			s.rightClick();
			Thread.sleep(1500);
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(10000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
		    Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);	
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			//Thread.sleep(200);
			//robo1.keyPress(KeyEvent.VK_TAB);
			//Thread.sleep(200);
			//robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(2000);
			Library.Interaction.writeKeyboardString(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.productCode"));
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			Library.Interaction.writeKeyboardString(robo1, "9");
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			Library.Interaction.writeKeyboardString(robo1, JsonParser.CommonData("ReadyFinnanceFData.RFData.productQuantity"));
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			//robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(700);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			//Day
			Library.Interaction.writeKeyboard(robo1, "29");
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.AddProductIcon"));
			s.mouseMove();
			Thread.sleep(1000);
			s.click();
			
			Thread.sleep(1500);
			try 
            {
            	 if(s.exists(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.OutOfStock"))!= null)
     		    { 
            		 robo1.keyPress(KeyEvent.VK_ENTER);
     		    }
     		else {
     				System.out.println("Product Out of stock popup not coming");
     			} 
				
			} 
            catch (Exception e) {
            	System.out.println("Product in stock");
			}
			
			Thread.sleep(4000);
			
            try 
            {
            	 if(s.exists(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.warrantyScreen"))!= null)
     		    { 
     		    s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.add"));
     		    s.mouseMove();
     			Thread.sleep(800);
     		    s.click();
     		    Thread.sleep(6000);
     		    s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.buy"));
     		    s.mouseMove();
     			Thread.sleep(800);
     		    s.click();
     		   Thread.sleep(1500);
     		   robo1.keyPress(KeyEvent.VK_ENTER);
     		    Thread.sleep(8000);
     		    }
     		else {
     				System.out.println("Warranty not Added to Product");
     			} 
				
			} 
            catch (Exception e) {
            	System.out.println("Product is not warrantable");
			}

			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2500);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.SaveIcon"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.CloseTab"));
			s.mouseMove();
			Thread.sleep(1000);
			s.click();
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			//Thread.sleep(4000);
			Thread.sleep(7000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.AccountNoBar"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(1500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(200);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(200);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.CloseTab"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			// Thread.sleep(10000);
			Thread.sleep(5000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.Transaction"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(200);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_V);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_V);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.PaymentCustID"));
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(4000);
			s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.PaymentAmmount"));
			//s.find("C:\\Users\\InfoGlobal_Tech3\\eclipse-workspace\\COSAC_CLIENT\\target\\PaymentAmmount.png");
			s.mouseMove();
			Thread.sleep(800);
			s.click();
			Thread.sleep(1500);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(20);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(100);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(100);
			robo1.keyRelease(KeyEvent.VK_CONTROL);

			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			
			//Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			//Library.Interaction.writeKeyboardString(robo1, JsonParser.RFAccount_Data("ReadyFinnanceFData.RFData.TenderedAmount"));
			// Library.Interaction.writeKeyboard(robo1, "10000");
			// Thread.sleep(3000);
			// s.find("C:\\Users\\InfoGlobal_Tech3\\eclipse-workspace\\COSAC_CLIENT\\target\\PaymentAmmount.png");
			// s.mouseMove();
			// Thread.sleep(500);
			// s.click();
			//Thread.sleep(2000);
			//s.find(JsonParser.getSikuliScreePath("ReadyFinScreensPath.NewCustReadyFinance.PayButton"));
			//s.mouseMove();
			//Thread.sleep(800);
			//s.click();
			Thread.sleep(13000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);

			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(5000);
			Library.Interaction.closeCosacClient(robo1);

			Thread.sleep(2000);

		} catch (Exception e) {
			e.getMessage();
			
			
			
		Assert.fail( e.getMessage());

			// windriver.close();
			/*
			 * s.find(JsonParser.getSikuliScreePath(
			 * "CashAndGoScreensPath.NewCustCASHAccount.Custome")); //Thread.sleep(5000);
			 * s.mouseMove(); Thread.sleep(3000); s.click();
			 */
		}

	}

}
