package com.cosac.TestCases;

import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.winium.WiniumDriver;
import org.sikuli.script.Screen;
import org.testng.annotations.Test;

import com.cosac.Locators.Id;
import com.cosac.PageObject.Library;
import com.cosac.PageObject.LoginPage;
import com.cosac.Utilities.JsonParser;

public class COS42_CreditCollections_CallCenter extends LoginPage {

	public String Credit = ".\\target\\COS42_68_69_70_106_107\\Credit.PNG";
	public String ViewReferences = ".\\target\\COS42_68_69_70_106_107\\ViewReferences.PNG";
	public String FollowUpActionDetails = ".\\target\\COS42_68_69_70_106_107\\FollowUpActionDetails.PNG";
	public String Return = ".\\target\\COS42_68_69_70_106_107\\Return.PNG";
	public String AddAccountCustomerCode = ".\\target\\COS42_68_69_70_106_107\\AddAccountCustomerCode.PNG";
	public String AddActCodes = ".\\target\\COS42_68_69_70_106_107\\AddActCodes.PNG";
	public String Play = ".\\target\\COS42_68_69_70_106_107\\Play.PNG";
	public String Add2 = ".\\target\\COS42_68_69_70_106_107\\Add2.PNG";
	public String AddCustCodes = ".\\target\\COS42_68_69_70_106_107\\AddCustCodes.PNG";
	public String AccountDetails = ".\\target\\COS42_68_69_70_106_107\\AccountDetails.PNG";
	public String CustomerDetails = ".\\target\\COS42_68_69_70_106_107\\CustomerDetails.PNG";
	public String OK = ".\\target\\COS42_68_69_70_106_107\\Ok.PNG";
	public String Brother_Sister = ".\\target\\COS42_68_69_70_106_107\\Brother-Sister.PNG";
	public String Friend = ".\\target\\COS42_68_69_70_106_107\\Friend.PNG";
	public String Cousin = ".\\target\\COS42_68_69_70_106_107\\Cousin.PNG";
	public String Landlord = ".\\target\\COS42_68_69_70_106_107\\Landlord.PNG";
	public String TelephoneActions = ".\\target\\COS42_68_69_70_106_107\\TelephoneActions.PNG";
	public String Home = ".\\target\\COS42_68_69_70_106_107\\Home.PNG";
	public String Work = ".\\target\\COS42_68_69_70_106_107\\Work.PNG";
	public String FollowUP = ".\\target\\COS42_68_69_70_106_107\\FollowUp.PNG";
	public String RightArrow = ".\\target\\COS42_68_69_70_106_107\\RightArrow.PNG";
	public String AddComment = ".\\target\\COS42_68_69_70_106_107\\AddComment.PNG";
	public String SaveButton = ".\\target\\COS42_68_69_70_106_107\\SaveButton.PNG";
	public String Parent = ".\\target\\COS42_68_69_70_106_107\\Parent.PNG";
	public String Aunt_Uncle = ".\\target\\COS42_68_69_70_106_107\\AuntUncle.PNG";

	LoginPage login = new LoginPage();


	@Test
	public void CallCenter() throws Throwable {

		try {

			login.LoginCosacClient();
			Thread.sleep(15000);
			Screen s = new Screen();
			Thread.sleep(5000);
			//s.find(Credit);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Credit"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Library.Interaction.print("User Selected on Credit Option");
			Thread.sleep(3000);
			Robot robo1 = new Robot();
			//robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on TelePhone Action Screen");
			Thread.sleep(27000);
			//s.find(ViewReferences); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.ViewReferences"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Library.Interaction.print("User clicked on View Reference Button");
			Thread.sleep(5000); 
            robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
            robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Friend Work Tel Number");
			String Friend_WorkTel = Library.Interaction.captureText();
			Library.Interaction.print("Friend WorkTel is:" + Friend_WorkTel);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
            robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Friend Mobile Tel Number ");
			String Friend_MobileTel=Library.Interaction.captureText();
			Library.Interaction.print("Friend Mobile Tel is:" + Friend_MobileTel);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
            robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Friend Phone Tel Number ");
			String Friend_PhoneTel = Library.Interaction.captureText();
			Library.Interaction.print("Friend PhoneTel is:" + Friend_PhoneTel);
            Library.Interaction.print(Friend_MobileTel+Friend_PhoneTel);
			Library.Interaction.userWait();
            //s.find(Brother_Sister); 
            s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Brother_Sister"));
			s.mouseMove(); Thread.sleep(500);
			s.click(); 
			Thread.sleep(2000);
			Library.Interaction.print("User clicked on Brother_Sister Tab"); 
            robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Brother/Sister MobileTel Number");
			String Brother_Sister_MobileTel = Library.Interaction.captureText();
			Library.Interaction.print("Brother_Sister_MobileTel is:" + Brother_Sister_MobileTel);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
            robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Brother/Sister Phone Number");
			String Brother_Sister_PhoneTel = Library.Interaction.captureText();
			Library.Interaction.print("Brother_Sister_MobileTel is:" + Brother_Sister_PhoneTel);
			Library.Interaction.userWait();
			Library.Interaction.print(Brother_Sister_MobileTel+Brother_Sister_PhoneTel);
			Library.Interaction.userWait();
			//s.find(Landlord); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Landlord"));
			s.mouseMove();
			Thread.sleep(500);
			s.click(); 
			Thread.sleep(2000);
			Library.Interaction.print("User clicked on Landlord Tab"); 
            robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Landlord Phone Number");
			Library.Interaction.userWait();
            String Landlord = Library.Interaction.captureText();
			Library.Interaction.print("Landlord is:" +Landlord);
			Library.Interaction.userWait();
			//s.find(TelephoneActions);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.TelephoneActions"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click(); 
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on TelephoneActions");
            //s.find(FollowUpActionDetails); 
            s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.FollowUpActionDetails"));
			s.mouseMove(); Thread.sleep(500); 
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on FollowUp Action Details button");
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_CONTROL); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User copied Account Number");
			Thread.sleep(2000);
			String Accountnumber = Library.Interaction.captureText();
			Library.Interaction.print(Accountnumber);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(2000); 
			robo1.keyPress(KeyEvent.VK_CONTROL); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User copied Date");
			Thread.sleep(2000);
			String Date=Library.Interaction.captureText();
			Library.Interaction.print(Date);
			//s.find(Return);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Return"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on Return button");
			Thread.sleep(3000); 
			//s.find(AddAccountCustomerCode);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.AddAccountCustomerCode"));
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on Add Account Customer Code button");
			Thread.sleep(5000);
			//s.find(AddActCodes); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.AddActCodes"));
			s.mouseMove(); 
			Thread.sleep(500);
			s.click(); 
			Thread.sleep(3000); 
			Library.Interaction.print("User clicked on Add Act Codes button");
			//s.find(Play); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Play"));
			s.mouseMove(); 
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on Play button");
			Thread.sleep(2000); 
			s.find(Add2); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Add2"));
			s.mouseMove(); 
			Thread.sleep(500);
			s.click(); 
			Library.Interaction.print("User clicked on Add button");
			Thread.sleep(3000);
			//s.find(AddCustCodes);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.AddCustCodes"));
			s.mouseMove(); 
			Thread.sleep(500);
			s.click(); 
			Thread.sleep(5000);
			Library.Interaction.print("User clicked on Add Cust Codes button");
			//s.find(Play);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Play"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(5000);
			Library.Interaction.print("User clicked on Play button"); 
            robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(3000);
            //s.find(Add2); 
            s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Add2"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(5000);
			Library.Interaction.print("User clicked on Add button"); 
			//s.find(TelephoneActions);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.TelephoneActions"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Library.Interaction.print("User clicked on TelephoneActions");
			Thread.sleep(5000); 
			//s.find(AccountDetails);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.AccountDetails"));
			s.mouseMove(); 
			Thread.sleep(500);
			s.click();
			Library.Interaction.print("User clicked on Account Details button");
			Thread.sleep(15000);
			s.find(Home); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Home"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on Home Tab"); 
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Home Phone Number");
			Library.Interaction.userWait();
            String HomePhone = Library.Interaction.captureText();
			Library.Interaction.print("Home Phone is:" +HomePhone);
			Library.Interaction.userWait();	
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Home Phone Number");
			String HomePhone2 = Library.Interaction.captureText();
			Library.Interaction.print("Home Phone2 is:" +HomePhone2);
			Library.Interaction.userWait();		
			Library.Interaction.print(HomePhone+HomePhone2);
			Library.Interaction.userWait();
			s.find(Work);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Work"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(5000);
			Library.Interaction.print("User clicked on Work Tab");  
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Work Phone Number");
			Library.Interaction.userWait();
			String WorkPhone = Library.Interaction.captureText();
			Library.Interaction.print("Work Phone is:" +WorkPhone);
			Library.Interaction.userWait();	
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Home Phone Number");
			String WorkPhone2 = Library.Interaction.captureText();
			Library.Interaction.print("Work Phone2 is:" +WorkPhone2);
			Library.Interaction.userWait();		
			Library.Interaction.print(WorkPhone+WorkPhone2);
			Library.Interaction.userWait();
			//s.find(RightArrow); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.RightArrow"));
			s.mouseMove(); 
			Thread.sleep(500);
			s.click();
			Library.Interaction.print("User clicked on Account Details button");
			Thread.sleep(5000);
			//s.find(FollowUP);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.FollowUP"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Library.Interaction.print("User clicked on FollowUP Tab");
			Thread.sleep(5000);
			//s.find(Play);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Play"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(2000);
			Library.Interaction.print("User clicked on Play Tab"); 
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB); 
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Library.Interaction.print("User Copied Date");
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Thread.sleep(2000);
			String FollowUpDate=Library.Interaction.captureText();
			Library.Interaction.print(FollowUpDate);
			Thread.sleep(5000);
			//s.find(TelephoneActions); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.TelephoneActions"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Library.Interaction.print("User clicked on TelephoneActions");
			Thread.sleep(5000);
			//s.find(CustomerDetails); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.CustomerDetails"));
			s.mouseMove();
			Thread.sleep(500); 
			s.click();
			Library.Interaction.print("User clicked on Customer Details Button");
			Thread.sleep(5000);
			//s.find(OK); 
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.OK"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Library.Interaction.print("User clicked on Customer Details Button");
			Thread.sleep(5000);
			//s.find(Home);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Home"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on Home Tab"); 
		    Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.userWait();
			Library.Interaction.print("User Copied Home Phone Number");

			String Address_HomePhone = Library.Interaction.captureText();
			Library.Interaction.print("Home Phone is:" +Address_HomePhone);
			Library.Interaction.userWait();	
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Home Phone Number");
			String Address_HomePhone2 = Library.Interaction.captureText();
			Library.Interaction.print("Home Phone2 is:" +Address_HomePhone2);
			Library.Interaction.userWait();		
			Library.Interaction.print(Address_HomePhone+Address_HomePhone2);
			Library.Interaction.userWait();
			
			//s.find(Work);
			s.find(JsonParser.getSikuliScreePath("CashAndGoScreensPath.NewCustCASHAccount.Work"));
			s.mouseMove(); 
			Thread.sleep(500); 
			s.click();
			Thread.sleep(5000);
			Library.Interaction.print("User clicked on Work Tab"); 
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(300);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.userWait();
			Library.Interaction.print("User Copied Work Phone Number");
			String Address_WorkPhone = Library.Interaction.captureText();
			Library.Interaction.print("Work Phone is:" +Address_WorkPhone);
			Library.Interaction.userWait();	
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_CONTROL);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C);
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copied Home Phone Number");
			String Address_WorkPhone2 = Library.Interaction.captureText();
			Library.Interaction.print("Work Phone2 is:" +Address_WorkPhone2);
			Library.Interaction.userWait();		
			Library.Interaction.print(WorkPhone+WorkPhone2);
			Library.Interaction.userWait();
			Thread.sleep(3000);
			Library.Interaction.closeCosacClient(robo1);
			/*
			 * robo1.keyPress(KeyEvent.VK_ALT); robo1.keyPress(KeyEvent.VK_SPACE);
			 * robo1.keyPress(KeyEvent.VK_C); robo1.keyRelease(KeyEvent.VK_C);
			 * robo1.keyRelease(KeyEvent.VK_SPACE); robo1.keyRelease(KeyEvent.VK_ALT);
			 */
			Library.Interaction.print("User clicked on Close Window"); 
			
		} catch (Exception e) 
		{
			e.printStackTrace();
			driver.close();
		}

	}

}
