package com.cosac.TestCases;
import java.awt.Robot;
import java.awt.event.KeyEvent;
//Here we are Creating and Verifying New Store Location in Country
import java.io.IOException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.winium.WiniumDriver;
import org.sikuli.script.Screen;
import org.testng.Assert;
import org.testng.annotations.Test;
import com.cosac.Locators.Id;
import com.cosac.Locators.Name;
import com.cosac.Locators.Xpath;
import com.cosac.PageObject.Library;
import com.cosac.PageObject.LoginPage;

public class COS69_Customise_Scoring_Rules extends LoginPage {

	String weight="5";
	public String System_Configuration=".\\target\\COS42_68_69_70_106_107\\System-Configuration.PNG";
	public String NewRules=".\\target\\COS42_68_69_70_106_107\\NewRules.PNG";
	public String Scorecard=".\\target\\COS42_68_69_70_106_107\\Scorecard.PNG";
	public String NewButton=".\\target\\COS42_68_69_70_106_107\\NewButton.PNG";
	public String Operand1=".\\target\\COS42_68_69_70_106_107\\Operand1.PNG";
	public String Comparison=".\\target\\COS42_68_69_70_106_107\\Comparison.PNG";
	public String Operand2=".\\target\\COS42_68_69_70_106_107\\Operand2.PNG";
	public String Add=".\\target\\COS42_68_69_70_106_107\\Add.PNG";
	public String ApplyToHP=".\\target\\COS42_68_69_70_106_107\\ApplytoHP.PNG";
	public String Weight=".\\target\\COS42_68_69_70_106_107\\Weight.PNG";
	public String SaveRule=".\\target\\COS42_68_69_70_106_107\\SaveRule.PNG";
    public String Close=".\\target\\COS42_68_69_70_106_107\\Close.PNG";
	LoginPage login= new LoginPage();

	@Test
	public void SystemConfigure() throws Throwable
	{
		try {
			login.LoginCosacClient();
			Thread.sleep(15000);
			Screen s=new Screen();
			Thread.sleep(5000);
			s.find(System_Configuration);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Library.Interaction.print("User clicked on System_Configuration");
			Thread.sleep(5000);
			Robot robo1=new Robot();
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(1000);
			
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_ENTER);

			Thread.sleep(3000);
			Library.Interaction.print("User clicked on Customise Score Rules");
			s.find(NewRules);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Library.Interaction.print("User clicked on New Rules");
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2000);
			Library.Interaction.print("User Selected on Scoring Rules");
			s.find(Scorecard);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
            Library.Interaction.print("User Selected on Scorecard");
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2000);
			s.find(NewButton);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User Clicked on NewButton");
			s.find(Operand1);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User Clicked on Operand1");
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(5000);
			//s.type("Maritalstatus_woe");
			robo1.keyPress(KeyEvent.VK_ENTER);
			Library.Interaction.print("User Selected Maritalstatus_woe");
			Thread.sleep(5000);
			s.find(Comparison);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(5000);
			Library.Interaction.print("User Clicked on Comparison drop down");
            s.type("=");
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2000);
			s.find(Operand2);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Thread.sleep(2000);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_DOWN);
			Thread.sleep(500);
			robo1.keyPress(KeyEvent.VK_ENTER);
			Library.Interaction.print("User Selected on Single-S");
            Thread.sleep(3000);
			s.find(Add);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User Clicked on Add Button");
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			s.find(ApplyToHP);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User Unchecked Apply To HP");
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_TAB);
			Thread.sleep(3000);
			Library.Interaction.writeKeyboard(robo1, weight);
			Thread.sleep(2000);
			Library.Interaction.print("User Entered Weight");
		    robo1.keyPress(KeyEvent.VK_CONTROL); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_A); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_A); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.userWait();
			robo1.keyPress(KeyEvent.VK_CONTROL); 
			Thread.sleep(1000);
			robo1.keyPress(KeyEvent.VK_C); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_C); 
			Thread.sleep(1000);
			robo1.keyRelease(KeyEvent.VK_CONTROL);
			Library.Interaction.print("User Copy the Account Number");
			Library.Interaction.userWait();
			String weight=Library.Interaction.captureText();
			Library.Interaction.print("Copied Weight is:"+weight);
			s.find(SaveRule);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User clicked on Save Rule Button");
			s.find(Close);
			s.mouseMove();
			Thread.sleep(500);
			s.click();
			Thread.sleep(3000);
			Library.Interaction.print("User Clicked on Close button");
			/*
			 * s.find(Close); s.mouseMove(); Thread.sleep(500); s.click();
			 * Thread.sleep(3000);
			 * Library.Interaction.print("User Clicked on Close button");
			 */
			Library.Interaction.closeCosacClient(robo1);
			Thread.sleep(2000);
			

		} catch (Exception e) {
			e.printStackTrace();
			
			driver.close();
		}



	}

}

